transparent = "#00000000"

fail = "#cc6e8f"
info = "#74add2"
success = "#65a884"
warn = "#fffac2"

dark = "#121c26"
light = "#202733"
main = "#1d232e"

accent_color = "#3c88b9"

ansi_black = "#000000"
ansi_red = "#f77172"
ansi_green = "#65a884"
ansi_yellow = "#cec999"
ansi_blue = "#74add2"
ansi_magenta = "#a980c4"
ansi_cyan = "#2d949f"
ansi_white = "#eeeeee"
