transparent = "#00000000"

fail = "#cc6e8f"
info = "#74add2"
success = "#65a884"
warn = "#fffac2"

dark = "#121c26"
light = "#202733"
main = "#1d232e"

accentColor = "#3c88b9"

ansiBlack = "#000000"
ansiRed = "#f77172"
ansiGreen = "#65a884"
ansiYellow = "#cec999"
ansiBlue = "#74add2"
ansiMagenta = "#a980c4"
ansiCyan = "#2d949f"
ansiWhite = "#eeeeee"
