name: Validate JSONs

run-name: ${{ github.actor }} is validating JSON files

on:
  pull_request:
    branches:
      - main
      - colors
      - tokens
  push:
    branches:
      - main
      - colors
      - tokens

jobs:
  validate-jsons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Pipenv setup
        run: pip install pipenv
      - name: Python dependencies
        run: pipenv install
      - name: Build theme files
        run: pipenv run python -m main
      - name: actions/json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "./themes/.*\\.json$"
